### ISSUE TITLE
DPS310/SCD40 Humidity missing...

### ISSUE THREAD

**Issue by steel4me** [ApolloAutomation/MSR-2#8]
I should return the working not defective second msr2 sensor too.

In your wiki/documentation you write about humidity.
https://wiki.apolloautomation.com/books/msr-2/page/msr-2-temperature-humidity-offsets

But there is and never was something in the config `Integrations/ESPHome/MSR-2.yaml` !?
Wiki and Documentation is just copy & paste from msr-1 !?

This is frustrating & annoying.

**Comment by steel4me** [comment]
@TrevorSchirmer are we just ignoring github issues? then close it!

**Comment by TrevorSchirmer** [comment]
Morning @steel4me , Is there an issue we missed? Github is probably our slowest form of support, we are highly active in discord https://discord.gg/mMNgQPyF94 I'm trying to figure out how to auto assign the issues because if I don't get tagged then the only way we see it is to happen to check the repo. I've been very busy the last few days with all the firmware changes but our support team in Discord or support@apolloautomation.com is always available.

Yes the MSR-2 does not have humidity in the base version. It does have it if you have the CO2 version. We have this wiki article to walk you through it: https://wiki.apolloautomation.com/books/general/page/how-to-add-temp-and-humidity-from-scd40


We added them as disabled entities on the MTR so it would probably be a good idea for us to add on MSR as well. We can get that updated.

I'll take a look at the wiki, thanks for pointing that out.

**Comment by steel4me** [comment]
Hello @TrevorSchirmer as far as it is end user support i agree. In this case it hast directly todo with things on your repo and wiki. but yes maybe im wrong and old or conservative because i strictly separate this in working life. I use discord when we play games. anyway, no matter we do the same for another private genre with forgejo and mattermost.

Normally issue and bug tracking should stay along the platform you put your code to repos. with associated and generated tags. just combine both worlds. take some of your discord bots, activate github webhooks and set triggers for issue/push/pull requests and fire them to the discord bot over api with token. Then you can write/post to your discords channels and know that something happened in the other world.

I was a bit pissed because one of my two sensors was broken and my RMA request was rejected, so I made use of the 14-day return policy. After installing the factory firmware on one of the two sensors, I did allow it to be integrated into my WLAN, but after that I couldn't access the web interface, it responded to a ping but nothing else. I flashed different firmware versions in boot mode, but nothing helped.

**Comment by TrevorSchirmer** [comment]
Yeah I've set up an action to assign me to issues/prs. Discord and email: support@apolloautomation.com will still be our fastest and best methods for support. But we handle issues through GitHub, Facebook, reddit as well.

Ok, sorry about your experience we can usually rectify any issue through reflashing or walking the customer through the import process. Very rarely does the sensor actually need replaced.


Are you still having a problem with one of our devices or have you returned them?

Thanks,
Trevor

**Comment by steel4me** [comment]
As i told. One is running fine. The other does not come up with webui. I go to discord and write but i bet the device is.....damaged and need to be replaced.
